# Generated by Django 3.1.5 on 2021-02-07 18:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('total_labor_cost', models.DecimalField(decimal_places=1, max_digits=8)),
                ('total_material_cost', models.DecimalField(decimal_places=1, max_digits=8)),
                ('total_item_price', models.DecimalField(decimal_places=1, max_digits=8)),
                ('total_sets', models.DecimalField(decimal_places=1, max_digits=8)),
                ('total_volume', models.IntegerField()),
                ('tax', models.DecimalField(decimal_places=1, max_digits=8)),
                ('bid_total', models.DecimalField(decimal_places=1, max_digits=8)),
                ('options_total', models.DecimalField(decimal_places=1, max_digits=8)),
                ('grand_total', models.DecimalField(decimal_places=1, max_digits=8)),
                ('notes', models.CharField(max_length=100)),
                ('terms', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_price', models.DecimalField(decimal_places=1, max_digits=8)),
                ('item_yield', models.DecimalField(decimal_places=1, max_digits=8)),
                ('item_thickness', models.DecimalField(decimal_places=1, max_digits=8)),
                ('labor_rate', models.DecimalField(decimal_places=1, max_digits=8)),
                ('item_total', models.DecimalField(decimal_places=1, max_digits=8)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relate_item', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_sqft', models.IntegerField()),
                ('line_thickness', models.DecimalField(decimal_places=1, max_digits=8)),
                ('line_pitch', models.IntegerField()),
                ('line_volume', models.IntegerField()),
                ('line_sets', models.DecimalField(decimal_places=1, max_digits=8)),
                ('line_item_price', models.DecimalField(decimal_places=1, max_digits=8)),
                ('line_material_cost', models.DecimalField(decimal_places=1, max_digits=8)),
                ('line_labor_cost', models.DecimalField(decimal_places=1, max_digits=8)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.bid')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_items', to='customer.item')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relate_lineitem', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('phone_num', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bid',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='customer.customer'),
        ),
        migrations.AddField(
            model_name='bid',
            name='line_item',
            field=models.ManyToManyField(through='customer.LineItem', to='customer.Item'),
        ),
        migrations.AddField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relate_bid', to=settings.AUTH_USER_MODEL),
        ),
    ]
